export { default as Home } from './Home/Home'
export {default as About} from './About/About'
export {default as Products} from './Products/Products'
export {default as News} from './News/News'
export { default as Contact } from './Contact/Contact'
export { default as ErrorPage } from './ErrorPage/ErrorPage'