export {default as Contact} from './contact/Contact'
export {default as News} from './news/News'
export {default as Home} from './home/Home'
export {default as Products} from './products/Products'
export {default as Product} from './product/Product'