export { default as Home} from './home/Home'
export { default as About} from './about/About'
export { default as Contact} from './contact/Contact'
export { default as Posts} from './posts/Posts'
export { default as Products} from './products/Products'
export { default as ErrorPage} from './errorPage/ErrorPage'
export { default as News} from './news/News'
export { default as Post} from './post/Post'